CREATE TABLE TBLCourse (
    id_course SERIAL PRIMARY KEY,
    name_course VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
