CREATE TABLE TBLSubject (
    id_subject SERIAL PRIMARY KEY,
    name_subject VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
